export enum LanguageText {
    Login_Username = 'Username',
    Login_Password = 'Password',
    Login_Confirm_Password = 'Confirm Password',
    Login_Email = 'Email',
    Btn_Login = 'Login',
    Btn_Login_Text = 'You already have an account?',
    Btn_Register = 'Register',
    Btn_Register_Text = 'You don\'t have an account yet?',
    Error_Notification_Login = 'Username or Password issue, please login again',
    Menu_Works = 'WORKS',
    Menu_Create = 'CREATE',
    Menu_Logout = 'LOGOUT',
    Success_Login = 'The login process was successful',
    Requirements_Username = 'Min 5 char length and contains only lowercase letters and digits, whitespace not allowed',
    Requirements_Password = 'Min 6 char length and contains only lower or uppercase letters and digits and special chars, whitespace not allowed',
    Requirements_Email = 'Please give a valid email format',
    Requirements_Confirm_Password = 'The two passwords are different',
}

export const LANG_EN: { [key in keyof typeof LanguageText]: string } = {
    Login_Username: 'Username',
    Login_Password: 'Password',
    Login_Confirm_Password: 'Confirm Password',
    Login_Email: 'Email',
    Btn_Login: 'Login',
    Btn_Login_Text: 'You already have an account?',
    Btn_Register: 'Register',
    Btn_Register_Text: 'You don\'t have an account yet?',
    Error_Notification_Login: 'Username or Password issue, please login again',
    Menu_Works: 'WORKS',
    Menu_Create: 'CREATE',
    Menu_Logout: 'LOGOUT',
    Success_Login: 'The login process was successful',
    Requirements_Username: 'Min 5 char length and contains only lowercase letters and digits, whitespace not allowed',
    Requirements_Password: 'Min 6 char length and contains only lower or uppercase letters and digits and special chars, whitespace not allowed',
    Requirements_Email: 'Please give a valid email format',
    Requirements_Confirm_Password: 'The two passwords are different',
};

export const LANG_HU: { [key in keyof typeof LanguageText]: string } = {
    Login_Username: 'Felhasználónév',
    Login_Password: 'Jelszó',
    Login_Confirm_Password: 'Jelszó Újra',
    Login_Email: 'Email',
    Btn_Login: 'Belépés',
    Btn_Login_Text: 'Már rigsztráltál?',
    Btn_Register: 'Regisztráció',
    Btn_Register_Text: 'Még nincs fiókod?',
    Error_Notification_Login: 'Felhasználónév vagy jelszó hiba, kérlek jelentkezz be újra',
    Menu_Works: 'MUNKÁK',
    Menu_Create: 'LÉTREHOZÁS',
    Menu_Logout: 'KILÉPÉS',
    Success_Login: 'A bejelentkezési folyamat sikeres volt',
    Requirements_Username: 'Min 5 karakter hosszú és csak kisbetűket és számokat tartalmazhat, szóköz nem megengedett',
    Requirements_Password: 'Min 6 karakter hosszú és tartalmazhat kis és nagybetűket, számokat, speciális karaktereket, szóköz nem megengedett',
    Requirements_Email: 'Kérem egy helyes email címet adjon meg',
    Requirements_Confirm_Password: 'A két jelszómező különböző',
};
